// ─── Cow Evolution Tiers ──────────────────────────────────────────────────────
// This is THE central progression axis. Each tier is a major milestone.

export const COW_TYPES = [
  {
    id: 'basic',
    index: 0,
    name: 'Basic Cow',
    emoji: '🐄',
    description: 'A humble, reliable start. Moo.',
    flavorText: 'Every dairy empire begins with one simple cow and a dream.',
    resource: 'milk',
    resourceName: 'Milk',
    resourceUnit: 'gal',
    resourceEmoji: '🥛',
    productionRate: 0.5,
    valuePerUnit: 1,
    unlockCost: 0,
    bgGradient: 'from-green-400 to-emerald-600',
    cardGradient: 'from-green-50 to-emerald-100',
    border: 'border-green-300',
    glowColor: 'rgba(34,197,94,0.4)',
    aura: null,
  },
  {
    id: 'jersey',
    index: 1,
    name: 'Jersey Cow',
    emoji: '🐮',
    description: 'Rich, buttery milk from a beloved dairy breed.',
    flavorText: 'Jersey milk has 18% more calcium. Your profits have 400% more.',
    resource: 'milk',
    resourceName: 'Premium Milk',
    resourceUnit: 'gal',
    resourceEmoji: '🥛',
    productionRate: 0.8,
    valuePerUnit: 5,
    unlockCost: 500,
    bgGradient: 'from-yellow-300 to-amber-500',
    cardGradient: 'from-yellow-50 to-amber-100',
    border: 'border-yellow-400',
    glowColor: 'rgba(251,191,36,0.4)',
    aura: null,
  },
  {
    id: 'holstein',
    index: 2,
    name: 'Holstein Cow',
    emoji: '🐄',
    description: 'The iconic black-and-white production powerhouse.',
    flavorText: "Holsteins produce 90% of U.S. milk. Soon they'll produce 90% of your money.",
    resource: 'milk',
    resourceName: 'Holstein Milk',
    resourceUnit: 'gal',
    resourceEmoji: '🥛',
    productionRate: 1.5,
    valuePerUnit: 25,
    unlockCost: 5000,
    bgGradient: 'from-slate-400 to-gray-600',
    cardGradient: 'from-gray-50 to-slate-100',
    border: 'border-gray-400',
    glowColor: 'rgba(148,163,184,0.4)',
    aura: null,
  },
  {
    id: 'angus',
    index: 3,
    name: 'Angus Dairy Cow',
    emoji: '🥩',
    description: 'A beefy pivot. These produce prime meat, not milk.',
    flavorText: "A detour into beef. A revelation. A very delicious side quest.",
    resource: 'meat',
    resourceName: 'Prime Beef',
    resourceUnit: 'lb',
    resourceEmoji: '🥩',
    productionRate: 0.4,
    valuePerUnit: 200,
    unlockCost: 75000,
    bgGradient: 'from-red-700 to-rose-900',
    cardGradient: 'from-red-50 to-rose-100',
    border: 'border-red-500',
    glowColor: 'rgba(239,68,68,0.4)',
    aura: null,
  },
  {
    id: 'chocolate',
    index: 4,
    name: 'Chocolate Milk Cow',
    emoji: '🍫',
    description: 'Scientifically impossible. Impossibly profitable.',
    flavorText: "You can't explain it. You can't question it. Just sell it.",
    resource: 'milk',
    resourceName: 'Chocolate Milk',
    resourceUnit: 'gal',
    resourceEmoji: '🍫',
    productionRate: 2.5,
    valuePerUnit: 2000,
    unlockCost: 2000000,
    bgGradient: 'from-amber-800 to-orange-900',
    cardGradient: 'from-amber-50 to-orange-100',
    border: 'border-amber-600',
    glowColor: 'rgba(180,83,9,0.5)',
    aura: 'shimmer',
  },
  {
    id: 'golden',
    index: 5,
    name: 'Golden Cow',
    emoji: '✨',
    description: 'A shimmering bovine miracle. Milk worth its weight in gold.',
    flavorText: 'Ancient alchemists searched for this. You bought it.',
    resource: 'milk',
    resourceName: 'Golden Milk',
    resourceUnit: 'gal',
    resourceEmoji: '✨',
    productionRate: 4,
    valuePerUnit: 10000,
    unlockCost: 50000000,
    bgGradient: 'from-yellow-400 to-amber-600',
    cardGradient: 'from-yellow-50 to-amber-100',
    border: 'border-yellow-500',
    glowColor: 'rgba(234,179,8,0.6)',
    aura: 'glow-gold',
  },
  {
    id: 'diamond',
    index: 6,
    name: 'Diamond Cow',
    emoji: '💎',
    description: 'Crystalline hooves, prismatic milk, infinite profit.',
    flavorText: "A geologist once tried to milk one. We don't speak of what happened.",
    resource: 'milk',
    resourceName: 'Diamond Milk',
    resourceUnit: 'gal',
    resourceEmoji: '💎',
    productionRate: 7,
    valuePerUnit: 2000000,
    unlockCost: 10000000000,
    bgGradient: 'from-cyan-400 to-blue-600',
    cardGradient: 'from-cyan-50 to-blue-100',
    border: 'border-cyan-400',
    glowColor: 'rgba(6,182,212,0.6)',
    aura: 'glow-diamond',
  },
  {
    id: 'cosmic',
    index: 7,
    name: 'Cosmic Cow',
    emoji: '🌟',
    description: 'Drifted in from a distant nebula. Produces celestial essence.',
    flavorText: "NASA tried to classify this. They couldn't. Neither can your bank.",
    resource: 'milk',
    resourceName: 'Cosmic Essence',
    resourceUnit: 'gal',
    resourceEmoji: '🌟',
    productionRate: 12,
    valuePerUnit: 1000000000,
    unlockCost: 50000000000000,
    bgGradient: 'from-purple-700 to-indigo-900',
    cardGradient: 'from-purple-50 to-indigo-100',
    border: 'border-purple-500',
    glowColor: 'rgba(147,51,234,0.6)',
    aura: 'glow-cosmic',
  },
  {
    id: 'mythic',
    index: 8,
    name: 'Mythic Moo Cow',
    emoji: '🌈',
    description: 'Ancient legends spoke of this being. Now it moos for you.',
    flavorText: 'Ancient cave paintings depict this moment. They seem both reverent and concerned.',
    resource: 'milk',
    resourceName: 'Mythic Essence',
    resourceUnit: 'gal',
    resourceEmoji: '🌈',
    productionRate: 25,
    valuePerUnit: 1e12,
    unlockCost: 1e19,
    bgGradient: 'from-pink-500 via-purple-600 to-indigo-700',
    cardGradient: 'from-pink-50 via-purple-50 to-indigo-100',
    border: 'border-pink-400',
    glowColor: 'rgba(236,72,153,0.7)',
    aura: 'glow-mythic',
  },
  {
    id: 'galactic',
    index: 9,
    name: 'Galactic Cow',
    emoji: '🚀',
    description: 'A cosmic deity of pure bovine energy. The final form.',
    flavorText: "You didn't build a farm. You built a religion. The universe moos.",
    resource: 'milk',
    resourceName: 'Galactic Essence',
    resourceUnit: 'gal',
    resourceEmoji: '🚀',
    productionRate: 60,
    valuePerUnit: 1e18,
    unlockCost: 1e26,
    bgGradient: 'from-indigo-900 via-violet-900 to-slate-900',
    cardGradient: 'from-indigo-50 via-violet-50 to-slate-100',
    border: 'border-indigo-400',
    glowColor: 'rgba(99,102,241,0.8)',
    aura: 'glow-galactic',
  },
];

// ─── Farm Tiers ───────────────────────────────────────────────────────────────
export const FARM_TIERS = [
  {
    id: 0,
    name: 'Backyard Pasture',
    emoji: '🏡',
    description: 'A humble patch of grass and big dreams.',
    maxCows: 10,
    cost: 0,
    bgGradient: 'from-green-300 to-emerald-500',
  },
  {
    id: 1,
    name: 'Small Family Farm',
    emoji: '🌾',
    description: 'A proper barn and enough room to grow.',
    maxCows: 30,
    cost: 2500,
    bgGradient: 'from-lime-400 to-green-500',
  },
  {
    id: 2,
    name: 'Dairy Ranch',
    emoji: '🏚️',
    description: 'Rolling fields as far as the eye can see.',
    maxCows: 75,
    cost: 30000,
    bgGradient: 'from-orange-300 to-amber-500',
  },
  {
    id: 3,
    name: 'Mega Milk Factory',
    emoji: '🏭',
    description: 'Industrial-scale production dominance.',
    maxCows: 200,
    cost: 400000,
    bgGradient: 'from-blue-400 to-blue-600',
  },
  {
    id: 4,
    name: 'Robotic Dairy Farm',
    emoji: '🤖',
    description: 'Fully automated. The robots handle the moo-ing.',
    maxCows: 500,
    cost: 6000000,
    bgGradient: 'from-violet-500 to-purple-700',
  },
  {
    id: 5,
    name: 'Sky Pasture',
    emoji: '☁️',
    description: 'Above the clouds, where the grass is always green.',
    maxCows: 1200,
    cost: 100000000,
    bgGradient: 'from-sky-400 to-cyan-500',
  },
  {
    id: 6,
    name: 'Moon Dairy Colony',
    emoji: '🌙',
    description: 'Low-gravity production. Cows float, yield soars.',
    maxCows: 3000,
    cost: 2000000000,
    bgGradient: 'from-slate-600 to-slate-800',
  },
  {
    id: 7,
    name: 'Galactic Moo Empire',
    emoji: '🚀',
    description: "You don't run a farm. You rule a dairy universe.",
    maxCows: 9999,
    cost: 50000000000,
    bgGradient: 'from-indigo-800 to-violet-900',
  },
];

// ─── Upgrades ─────────────────────────────────────────────────────────────────
export const UPGRADES = [
  {
    id: 'better_feed',
    name: 'Better Feed',
    emoji: '🌾',
    description: 'Premium nutrition boosts production per cow by 50% per level.',
    baseCost: 50,
    costMultiplier: 2.2,
    maxLevel: 25,
    category: 'production',
  },
  {
    id: 'bigger_barn',
    name: 'Bigger Barn',
    emoji: '🏚️',
    description: 'Expand your barn — +5 max cows per level.',
    baseCost: 100,
    costMultiplier: 1.9,
    maxLevel: 30,
    category: 'capacity',
  },
  {
    id: 'larger_tank',
    name: 'Larger Storage',
    emoji: '🥛',
    description: 'Bigger holding tanks — +50% storage per level.',
    baseCost: 75,
    costMultiplier: 2.0,
    maxLevel: 20,
    category: 'storage',
  },
  {
    id: 'faster_trucks',
    name: 'Faster Trucks',
    emoji: '🚚',
    description: 'Turbo-charged delivery fleet — +50% sell speed per level.',
    baseCost: 300,
    costMultiplier: 2.5,
    maxLevel: 15,
    category: 'sales',
  },
  {
    id: 'auto_herder',
    name: 'Auto Herder',
    emoji: '🤠',
    description: 'A robo-cowboy automatically adds cows over time.',
    baseCost: 750,
    costMultiplier: 3.5,
    maxLevel: 10,
    category: 'automation',
  },
  {
    id: 'robotic_milker',
    name: 'Robotic Milker',
    emoji: '🤖',
    description: 'Doubles all production per level.',
    baseCost: 2500,
    costMultiplier: 3.0,
    maxLevel: 10,
    category: 'production',
  },
  {
    id: 'premium_brand',
    name: 'Premium Brand',
    emoji: '💰',
    description: 'Luxury marketing — +50% sale price per level.',
    baseCost: 5000,
    costMultiplier: 3.0,
    maxLevel: 10,
    category: 'sales',
  },
];

// ─── Achievements ─────────────────────────────────────────────────────────────
export const ACHIEVEMENTS = [
  {
    id: 'first_cow',
    name: 'Got Milk?',
    emoji: '🐄',
    description: 'Send your first cow to the pasture.',
    check: (s) => s.cows >= 1,
  },
  {
    id: 'ten_cows',
    name: 'Small Herd',
    emoji: '🐮',
    description: 'Grow your herd to 10 cows.',
    check: (s) => s.cows >= 10,
  },
  {
    id: 'fifty_cows',
    name: 'Moo Crew',
    emoji: '🌿',
    description: 'Manage a herd of 50 cows.',
    check: (s) => s.cows >= 50,
  },
  {
    id: 'hundred_cows',
    name: 'Hundred Strong',
    emoji: '💪',
    description: 'Lead a herd of 100 mighty cows.',
    check: (s) => s.cows >= 100,
  },
  {
    id: 'first_sale',
    name: 'First Delivery',
    emoji: '🚚',
    description: 'Complete your first delivery.',
    check: (s) => s.totalMoneyEarned >= 1,
  },
  {
    id: 'thousandaire',
    name: 'Thousandaire',
    emoji: '💵',
    description: 'Earn $1,000 in total.',
    check: (s) => s.totalMoneyEarned >= 1000,
  },
  {
    id: 'millionaire',
    name: 'Dairy Millionaire',
    emoji: '💰',
    description: 'Earn $1,000,000 in total.',
    check: (s) => s.totalMoneyEarned >= 1e6,
  },
  {
    id: 'billionaire',
    name: 'Moo Billionaire',
    emoji: '💎',
    description: 'Earn $1,000,000,000 in total.',
    check: (s) => s.totalMoneyEarned >= 1e9,
  },
  {
    id: 'jersey_evolved',
    name: 'Step Up',
    emoji: '🐮',
    description: 'Evolve to Jersey Cow.',
    check: (s) => s.cowTypeIndex >= 1,
  },
  {
    id: 'angus_evolved',
    name: 'Beefy Detour',
    emoji: '🥩',
    description: 'Evolve to Angus Dairy Cow.',
    check: (s) => s.cowTypeIndex >= 3,
  },
  {
    id: 'golden_evolved',
    name: 'All That Glitters',
    emoji: '✨',
    description: 'Evolve to Golden Cow.',
    check: (s) => s.cowTypeIndex >= 5,
  },
  {
    id: 'cosmic_evolved',
    name: 'Stellar Farmer',
    emoji: '🌟',
    description: 'Evolve to Cosmic Cow.',
    check: (s) => s.cowTypeIndex >= 7,
  },
  {
    id: 'galactic_evolved',
    name: 'Divine Bovine',
    emoji: '🚀',
    description: 'Evolve to Galactic Cow.',
    check: (s) => s.cowTypeIndex >= 9,
  },
  {
    id: 'resource_1k',
    name: 'Fresh from the Farm',
    emoji: '🥛',
    description: 'Produce 1,000 units of resource total.',
    check: (s) => s.totalMilkProduced >= 1000,
  },
  {
    id: 'resource_million',
    name: 'Production Mogul',
    emoji: '🌊',
    description: 'Produce 1,000,000 units total.',
    check: (s) => s.totalMilkProduced >= 1e6,
  },
  {
    id: 'upgrade_5',
    name: 'Upgrade Addict',
    emoji: '⬆️',
    description: 'Purchase 5 total upgrade levels.',
    check: (s) => Object.values(s.upgrades).reduce((a, b) => a + b, 0) >= 5,
  },
  {
    id: 'upgrade_20',
    name: 'Power Shopper',
    emoji: '🛒',
    description: 'Purchase 20 total upgrade levels.',
    check: (s) => Object.values(s.upgrades).reduce((a, b) => a + b, 0) >= 20,
  },
  {
    id: 'first_prestige',
    name: 'Starting Over',
    emoji: '♻️',
    description: 'Prestige for the first time.',
    check: (s) => s.prestigeCount >= 1,
  },
  {
    id: 'reach_factory',
    name: 'Industrial Revolution',
    emoji: '🏭',
    description: 'Unlock the Mega Milk Factory.',
    check: (s) => s.currentFarm >= 3,
  },
  {
    id: 'mps_100',
    name: 'Milk Machine',
    emoji: '⚡',
    description: 'Reach 100 production/second.',
    check: (s) => s.milkPerSecond >= 100,
  },
  {
    id: 'mps_10k',
    name: 'Mega Producer',
    emoji: '🏆',
    description: 'Reach 10,000 production/second.',
    check: (s) => s.milkPerSecond >= 10000,
  },
  {
    id: 'streak_7',
    name: 'Dedicated Farmer',
    emoji: '📅',
    description: 'Log in 7 days in a row.',
    check: (s) => s.dailyStreak >= 7,
  },
];
