export const COW_BREEDS = [
  {
    id: 'backyard',
    name: 'Backyard Cow',
    emoji: '🐄',
    description: 'A simple, lovable cow. Every empire starts somewhere.',
    milkPerSecond: 0.5,
    unlockCost: 0,
    color: 'from-amber-100 to-amber-200',
    border: 'border-amber-300',
  },
  {
    id: 'jersey',
    name: 'Jersey Cow',
    emoji: '🐮',
    description: 'Creamy, rich milk with a hint of golden sweetness.',
    milkPerSecond: 3,
    unlockCost: 500,
    color: 'from-yellow-100 to-yellow-200',
    border: 'border-yellow-400',
  },
  {
    id: 'holstein',
    name: 'Holstein Cow',
    emoji: '🐄',
    description: 'The iconic black-and-white dairy powerhouse.',
    milkPerSecond: 15,
    unlockCost: 5000,
    color: 'from-gray-100 to-gray-200',
    border: 'border-gray-400',
  },
  {
    id: 'chocolate',
    name: 'Chocolate Milk Cow',
    emoji: '🍫',
    description: 'Scientists say it\'s impossible. Science is wrong.',
    milkPerSecond: 75,
    unlockCost: 60000,
    color: 'from-amber-800 to-amber-900',
    border: 'border-amber-600',
    textLight: true,
  },
  {
    id: 'golden',
    name: 'Golden Cow',
    emoji: '✨',
    description: 'A shimmering bovine legend, touched by fortune itself.',
    milkPerSecond: 400,
    unlockCost: 600000,
    color: 'from-yellow-300 to-amber-400',
    border: 'border-yellow-500',
  },
  {
    id: 'cosmic',
    name: 'Cosmic Cow',
    emoji: '🌟',
    description: 'Drifted in from a distant nebula. Smells like stardust.',
    milkPerSecond: 2000,
    unlockCost: 8000000,
    color: 'from-purple-600 to-indigo-700',
    border: 'border-purple-400',
    textLight: true,
  },
  {
    id: 'diamond',
    name: 'Diamond Dairy Cow',
    emoji: '💎',
    description: 'Crystalline perfection in bovine form. Handle with care.',
    milkPerSecond: 15000,
    unlockCost: 100000000,
    color: 'from-cyan-200 to-blue-300',
    border: 'border-cyan-400',
  },
  {
    id: 'mythic',
    name: 'Mythic Moo Cow',
    emoji: '🌈',
    description: 'Ancient texts spoke of this day. You have arrived.',
    milkPerSecond: 100000,
    unlockCost: 2000000000,
    color: 'from-pink-400 via-purple-400 to-indigo-400',
    border: 'border-pink-400',
    textLight: true,
  },
];

export const FARM_TIERS = [
  {
    id: 0,
    name: 'Backyard Pasture',
    emoji: '🏡',
    description: 'A humble patch of grass and big dreams.',
    maxCows: 10,
    cost: 0,
    bgClass: 'from-green-400 to-emerald-500',
  },
  {
    id: 1,
    name: 'Small Family Farm',
    emoji: '🌾',
    description: 'A proper barn and enough room to grow.',
    maxCows: 30,
    cost: 2500,
    bgClass: 'from-lime-400 to-green-500',
  },
  {
    id: 2,
    name: 'Dairy Ranch',
    emoji: '🏚️',
    description: 'Rolling fields as far as the eye can see.',
    maxCows: 75,
    cost: 30000,
    bgClass: 'from-orange-300 to-amber-500',
  },
  {
    id: 3,
    name: 'Mega Milk Factory',
    emoji: '🏭',
    description: 'Industrial-scale dairy production dominance.',
    maxCows: 200,
    cost: 400000,
    bgClass: 'from-blue-400 to-blue-600',
  },
  {
    id: 4,
    name: 'Robotic Dairy Farm',
    emoji: '🤖',
    description: 'Fully automated. The robots handle the moo-ing.',
    maxCows: 500,
    cost: 6000000,
    bgClass: 'from-violet-500 to-purple-700',
  },
  {
    id: 5,
    name: 'Sky Pasture',
    emoji: '☁️',
    description: 'Above the clouds, where the grass is always green.',
    maxCows: 1200,
    cost: 100000000,
    bgClass: 'from-sky-400 to-cyan-500',
  },
  {
    id: 6,
    name: 'Moon Dairy Colony',
    emoji: '🌙',
    description: 'Low-gravity milk production. Cows float, yield soars.',
    maxCows: 3000,
    cost: 2000000000,
    bgClass: 'from-slate-600 to-slate-800',
  },
  {
    id: 7,
    name: 'Galactic Moo Empire',
    emoji: '🚀',
    description: 'You don\'t run a farm. You rule a dairy universe.',
    maxCows: 9999,
    cost: 50000000000,
    bgClass: 'from-indigo-800 to-violet-900',
  },
];

export const UPGRADES = [
  {
    id: 'better_feed',
    name: 'Better Feed',
    emoji: '🌾',
    description: 'Premium grain blend boosts milk per cow by 50% per level.',
    baseCost: 50,
    costMultiplier: 2.2,
    maxLevel: 25,
    category: 'production',
  },
  {
    id: 'bigger_barn',
    name: 'Bigger Barn',
    emoji: '🏚️',
    description: 'Expand your barn to house 5 more cows per level.',
    baseCost: 100,
    costMultiplier: 1.9,
    maxLevel: 30,
    category: 'capacity',
  },
  {
    id: 'larger_tank',
    name: 'Larger Tank',
    emoji: '🥛',
    description: 'Bigger milk tanks hold 50% more per level.',
    baseCost: 75,
    costMultiplier: 2.0,
    maxLevel: 20,
    category: 'storage',
  },
  {
    id: 'faster_trucks',
    name: 'Faster Trucks',
    emoji: '🚚',
    description: 'Turbo-charge your delivery fleet. +50% sell speed per level.',
    baseCost: 300,
    costMultiplier: 2.5,
    maxLevel: 15,
    category: 'sales',
  },
  {
    id: 'auto_herder',
    name: 'Auto Herder',
    emoji: '🤠',
    description: 'A robo-cowboy automatically adds cows over time.',
    baseCost: 750,
    costMultiplier: 3.5,
    maxLevel: 10,
    category: 'automation',
  },
  {
    id: 'robotic_milker',
    name: 'Robotic Milker',
    emoji: '🤖',
    description: 'Doubles all milk production per level. Moo-tastic.',
    baseCost: 2500,
    costMultiplier: 3.0,
    maxLevel: 10,
    category: 'production',
  },
  {
    id: 'premium_brand',
    name: 'Premium Dairy Brand',
    emoji: '💰',
    description: 'Your milk commands a luxury price. +50% sale price per level.',
    baseCost: 5000,
    costMultiplier: 3.0,
    maxLevel: 10,
    category: 'sales',
  },
];

export const ACHIEVEMENTS = [
  {
    id: 'first_cow',
    name: 'Got Milk?',
    emoji: '🐄',
    description: 'Send your first cow to the pasture.',
    check: (s) => s.cows >= 1,
  },
  {
    id: 'ten_cows',
    name: 'Small Herd',
    emoji: '🐮',
    description: 'Grow your herd to 10 cows.',
    check: (s) => s.cows >= 10,
  },
  {
    id: 'fifty_cows',
    name: 'Moo Crew',
    emoji: '🌿',
    description: 'Manage a herd of 50 cows.',
    check: (s) => s.cows >= 50,
  },
  {
    id: 'hundred_cows',
    name: 'Hundred Strong',
    emoji: '💪',
    description: 'Lead a herd of 100 mighty cows.',
    check: (s) => s.cows >= 100,
  },
  {
    id: 'five_hundred_cows',
    name: 'Bovine Army',
    emoji: '⚔️',
    description: 'Command 500 cows.',
    check: (s) => s.cows >= 500,
  },
  {
    id: 'first_sale',
    name: 'First Delivery',
    emoji: '🚚',
    description: 'Complete your first milk delivery.',
    check: (s) => s.totalMoneyEarned >= 1,
  },
  {
    id: 'thousandaire',
    name: 'Dairy Thousandaire',
    emoji: '💵',
    description: 'Earn $1,000 in total sales.',
    check: (s) => s.totalMoneyEarned >= 1000,
  },
  {
    id: 'millionaire',
    name: 'Dairy Millionaire',
    emoji: '💰',
    description: 'Earn $1,000,000 in total sales.',
    check: (s) => s.totalMoneyEarned >= 1000000,
  },
  {
    id: 'billionaire',
    name: 'Moo Billionaire',
    emoji: '💎',
    description: 'Earn $1,000,000,000 in total sales.',
    check: (s) => s.totalMoneyEarned >= 1000000000,
  },
  {
    id: 'milk_1k',
    name: 'Fresh from the Farm',
    emoji: '🥛',
    description: 'Produce 1,000 gallons of milk total.',
    check: (s) => s.totalMilkProduced >= 1000,
  },
  {
    id: 'milk_million',
    name: 'Milk Mogul',
    emoji: '🌊',
    description: 'Produce 1,000,000 gallons of milk total.',
    check: (s) => s.totalMilkProduced >= 1000000,
  },
  {
    id: 'milk_billion',
    name: 'Lactose Titan',
    emoji: '🌍',
    description: 'Produce 1,000,000,000 gallons of milk.',
    check: (s) => s.totalMilkProduced >= 1000000000,
  },
  {
    id: 'upgrade_5',
    name: 'Upgrade Addict',
    emoji: '⬆️',
    description: 'Purchase 5 total upgrade levels.',
    check: (s) => Object.values(s.upgrades).reduce((a, b) => a + b, 0) >= 5,
  },
  {
    id: 'upgrade_20',
    name: 'Power Shopper',
    emoji: '🛒',
    description: 'Purchase 20 total upgrade levels.',
    check: (s) => Object.values(s.upgrades).reduce((a, b) => a + b, 0) >= 20,
  },
  {
    id: 'first_prestige',
    name: 'Starting Over',
    emoji: '♻️',
    description: 'Sell your farm and prestige for the first time.',
    check: (s) => s.prestigeCount >= 1,
  },
  {
    id: 'five_prestige',
    name: 'Serial Farmer',
    emoji: '🔄',
    description: 'Prestige 5 times.',
    check: (s) => s.prestigeCount >= 5,
  },
  {
    id: 'reach_factory',
    name: 'Industrial Revolution',
    emoji: '🏭',
    description: 'Unlock the Mega Milk Factory.',
    check: (s) => s.currentFarm >= 3,
  },
  {
    id: 'reach_space',
    name: 'Ad Astra',
    emoji: '🚀',
    description: 'Reach the Sky Pasture.',
    check: (s) => s.currentFarm >= 5,
  },
  {
    id: 'unlock_golden',
    name: 'All That Glitters',
    emoji: '✨',
    description: 'Unlock the legendary Golden Cow.',
    check: (s) => s.unlockedBreeds?.includes('golden'),
  },
  {
    id: 'unlock_mythic',
    name: 'Divine Bovine',
    emoji: '🌈',
    description: 'Unlock the Mythic Moo Cow.',
    check: (s) => s.unlockedBreeds?.includes('mythic'),
  },
  {
    id: 'mps_100',
    name: 'Milk Machine',
    emoji: '⚡',
    description: 'Reach 100 milk/second.',
    check: (s) => s.milkPerSecond >= 100,
  },
  {
    id: 'mps_10k',
    name: 'Mega Producer',
    emoji: '🏆',
    description: 'Reach 10,000 milk/second.',
    check: (s) => s.milkPerSecond >= 10000,
  },
];
